{{- range $.Values.collectors }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-{{ .id }}
  labels:
    app: acm-{{ .id }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: acm-{{ .id }}
  template:
    metadata:
      labels:
        app: acm-{{ .id }}
      annotations:
        apc/version: {{ $.Values.apc.version }}
        checksum/config: {{ include (print $.Template.BasePath "/common-configmap.yaml") $ | sha256sum }}
        checksum/acm-config: {{ include (print $.Template.BasePath "/acm/acm-configmap.yaml") $ | sha256sum }}
    spec:
      {{- if $.Values.hosts }}
      hostAliases:
        {{- range $.Values.hosts }}
        - ip: {{ .ip | quote }}
          hostnames:
          {{- range .hostnames }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if $.Values.ca_certificates }}
      volumes:
        - name: ca-certificates-config-volume
          configMap:
            name: common-env-config
      {{- end }}
      containers:
        - name: acm-{{ .id }}
          image: {{ .image }}:{{ .tag }}
          {{- if $.Values.ca_certificates }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/ca-certificates.crt 
              name: ca-certificates-config-volume 
              subPath: ca-certificates.crt
          {{- end }}
          {{- if .env }}
          env:
            {{- range $key, $val := .env }}
            - name: {{ $val.name }}
              value: {{ $val.value | quote }}
            {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: common-env-config
            - configMapRef:
                name: acm-env-config
{{- end}}
