apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-env-config
data:
  # Your environment variables go here
  ACM_S3_ACCESS_KEY: {{ .Values.s3.accessKey | quote }}
  ACM_S3_SECRET_KEY: {{ .Values.s3.secretKey | quote }}
  ACM_S3_REGION: {{ .Values.s3.region | quote }}
  ACM_S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  ACM_S3_BUCKET: {{ .Values.s3.bucket | quote }}
  APC_ACM_DIR: "/data"
  