---
# ACM Router (routes to the correct protocol collector)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-router
spec:
  replicas: {{ .Values.router.replicas }} 
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: acm-router
  template:
    metadata:
      labels:
        app: acm-router
      annotations:
        apc/version: {{ .Values.apc.version }}
        checksum/config: {{ include (print $.Template.BasePath "/common-configmap.yaml") . | sha256sum }}
    spec:
      {{- if $.Values.hosts }}
      hostAliases:
        {{- range $.Values.hosts }}
        - ip: {{ .ip | quote }}
          hostnames:
          {{- range .hostnames }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - image: ghcr.io/linus-berg/apc/acm/router:{{ .Values.apc.version }} 
          name: acm-router
          envFrom:
            - configMapRef:
                name: common-env-config
