---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-api
spec:
  replicas: {{ .Values.api.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apc-api
  template:
    metadata:
      labels:
        app: apc-api
      annotations:
        apc/version: {{ .Values.apc.version }}
        checksum/config: {{ include (print $.Template.BasePath "/common-configmap.yaml") . | sha256sum }}
        checksum/api-config: {{ include (print $.Template.BasePath "/api/api-configmap.yaml") . | sha256sum }}
        checksum/keycloak-config: {{ include (print $.Template.BasePath "/api/keycloak-configmap.yaml") . | sha256sum }}
    spec:
      {{- if $.Values.hosts }}
      hostAliases:
        {{- range $.Values.hosts }}
        - ip: {{ .ip | quote }}
          hostnames:
          {{- range .hostnames }}
            - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        - name: keycloak-config-volume
          configMap:
            name: keycloak-config
      {{- if $.Values.ca_certificates }}
        - name: ca-certificates-config-volume
          configMap:
            name: common-env-config
      {{- end }}
      containers:
        - image: ghcr.io/linus-berg/apc/api:{{ .Values.apc.version }} 
          name: apc-api
          volumeMounts:
            - mountPath: /app/keycloak.json
              subPath: keycloak.json
              name: keycloak-config-volume 
          {{- if $.Values.ca_certificates }}
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: ca-certificates-config-volume
              subPath: ca-certificates.crt
          {{- end }}
          envFrom:
            - configMapRef:
                name: common-env-config
            - configMapRef:
                name: api-env-config
          ports:
          - containerPort: 80
