---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-ingestion
spec:
  replicas: {{ required ".Values.ingestion.replicas must be set" .Values.ingestion.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apc-ingestion
  template:
    metadata:
      labels:
        app: apc-ingestion
      annotations:
        apc/version: {{ .Values.apc.version }}
        checksum/config: {{ include (print $.Template.BasePath "/common-configmap.yaml") . | sha256sum }}
        checksum/ingestion-config: {{ include (print $.Template.BasePath "/ingestion/ingestion-configmap.yaml") . | sha256sum }}
    spec:
      {{- if $.Values.hosts }}
      hostAliases:
        {{- range $.Values.hosts }}
        - ip: {{ .ip | quote }}
          hostnames:
          {{- range .hostnames }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - image: ghcr.io/linus-berg/apc/ingestion:{{ required ".Values.apc.version version must be set" .Values.apc.version }} 
          name: apc-ingestion
          envFrom:
            - configMapRef:
                name: common-env-config
            - configMapRef:
                name: ingestion-env-config
