{{- range .Values.processors }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-{{ .id }}
  labels:
    app: apm-{{ .id }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: apm-{{ .id }}
  template:
    metadata:
      labels:
        app: apm-{{ .id }}
    spec:
      {{- if $.Values.hosts }}
      {{- range $.Values.hosts }}
      hostAliases:
        - ip: {{ .ip | quote }}
          hostnames:
          {{- range .hostnames }}
          - {{ . | quote }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- if $.Values.ca_certificates }}
      volumes:
        - name: ca-certificates-config-volume
          configMap:
            name: common-env-config
      {{- end }}
      containers:
        - name: apm-{{ .id }}
          image: {{ .image }}:{{ .tag }}
          {{- if .env }}
          env:
            {{- range $key, $val := .env }}
            {{ $val.name }}: {{ $val.value | quote }}
            {{- end }}
          {{- end }}
          {{- if $.Values.ca_certificates }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/ca-certificates.crt 
              name: ca-certificates-config-volume
              subPath: ca-certificates.crt
          {{- end }}
          envFrom:
            - configMapRef:
                name: common-env-config
{{- end}}
