apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-env-config
data:
  # Your environment variables go here
  ACM_S3_ACCESS_KEY: {{ .Values.s3_access_key }}
  ACM_S3_SECRET_KEY: {{ .Values.s3_secret_key }}
  ACM_S3_REGION: {{ .Values.s3_region }}
  ACM_S3_ENDPOINT: {{ .Values.s3_endpoint }}
  ACM_S3_BUCKET: {{ .Values.s3_bucket }}
