apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env-config
data:
  # Your environment variables go here
  APC_RABBIT_MQ_HOST: {{ .Values.rabbitmq.host }}
  APC_RABBIT_MQ_USER: {{ .Values.rabbitmq.username }}
  APC_RABBIT_MQ_PASS: {{ .Values.rabbitmq.password }}
{{- if .Values.otel }}
  APC_OTEL_HOST: {{ .Values.otel.host }}
{{- end }}
{{- if .Values.no_proxy }}
  NO_PROXY: {{ join "," .Values.no_proxy  }}
  no_proxy: {{ join "," .Values.no_proxy }}
{{- end }}
{{- if .Values.http_proxy }}
  HTTP_PROXY: {{ .Values.http_proxy  }}
  HTTPS_PROXY: {{ .Values.http_proxy  }}
  http_proxy: {{ .Values.http_proxy  }}
  https_proxy: {{ .Values.http_proxy  }}
{{- end }}
