---
apiVersion: v1
kind: Service
metadata:
  name: apc-api
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: {{ .Values.api.loadbalancerIP }}
  selector:
    app: apc-api