---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak.json: |
    {
      "realm": "{{ .Values.keycloak.realm }}",
      "auth-server-url": "{{ .Values.keycloak.host }}",
      "ssl-required": "external",
      "resource": "{{ .Values.keycloak.resource }}",
      "public-client": true,
      "verify-token-audience": false,
      "use-resource-role-mappings": true,
      "confidential-port": 0
    }