---
apiVersion: v1
kind: Service
metadata:
  name: apc-gui
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.gui.port }}
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: {{ .Values.gui.loadBalancerIP }}
  selector:
    app: apc-gui
